# Standards: 1.2
---
- name: Write sudoers config
  ansible.builtin.template:
    src: sudoers.j2
    dest: /etc/sudoers
    validate: /usr/sbin/visudo -cf %s
    owner: root
    group: root
    mode: u=r,g=r,o=
  tags:
    - sudo

...
