# Standards: 1.2
---
- name: Install required packages
  community.general.rpm_ostree_pkg:
    name: python3-psutil
    state: present
  tags:
    - dconf

- name: Check boot status
  changed_when: False
  register: dconf_booted_check
  ansible.builtin.shell: rpm-ostree status --json | jq -r .deployments[0].booted
  tags:
    - dconf

- name: Live apply changes
  when: dconf_booted_check.stdout == 'false'
  ansible.builtin.command: rpm-ostree apply-live --allow-replacement
  tags:
    - dconf

...
