# Standards: 1.2
---
# @var sudo_secure_path:description: List of secure executable paths
sudo_secure_path:
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin

# @var sudo_env_keep:description: List of environment to keep
sudo_env_keep:
  - COLORS
  - DISPLAY
  - HOSTNAME
  - HISTSIZE
  - KDEDIR
  - LS_COLORS
  - MAIL
  - QTDIR
  - USERNAME
  - LANG
  - LC_ADDRESS
  - LC_CTYPE
  - LC_COLLATE
  - LC_IDENTIFICATION
  - LC_MEASUREMENT
  - LC_MESSAGES
  - LC_MONETARY
  - LC_NAME
  - LC_NUMERIC
  - LC_PAPER
  - LC_TELEPHONE
  - LC_TIME
  - LC_ALL
  - LANGUAGE
  - LINGUAS
  - _XKB_CHARSET
  - XAUTHORITY

...
