# Standards: 1.2
---
libvirt_networks:
  - name: general
    bridge: virbr1
    autostart: True
    mode: nat
    address: 10.13.37.1
    netmask: 255.255.255.0
    dhcp:
      enabled: True
      start: 10.13.37.2
      end: 10.13.37.254
    hosts: []

libvirt_machines: []

...
