# Standards: 1.2
---
- name: Check for requirements
  register: libvirt_package_check
  changed_when: False
  failed_when: False
  ansible.builtin.command: rpm -q libvirt
  tags:
    - libvirt

- name: Include layers tasks
  when: libvirt_package_check.rc > 0
  ansible.builtin.include_tasks: layers.yml
  tags:
    - libvirt

- name: Include libvirt tasks
  ansible.builtin.include_tasks: libvirt.yml
  tags:
    - libvirt

- name: Include images tasks
  ansible.builtin.include_tasks: images.yml
  tags:
    - libvirt
    - images

- name: Include networks tasks
  ansible.builtin.include_tasks: networks.yml
  tags:
    - libvirt
    - networks

- name: Include machines tasks
  ansible.builtin.include_tasks: machines.yml
  tags:
    - libvirt
    - machines

...
