# Standards: 1.2
---
- name: Include libvirt tasks
  ansible.builtin.include_tasks: libvirt.yml
  tags:
    - libvirt

- name: Include images tasks
  ansible.builtin.include_tasks: images.yml
  tags:
    - libvirt
    - images

- name: Include networks tasks
  ansible.builtin.include_tasks: networks.yml
  tags:
    - libvirt
    - networks

- name: Include machines tasks
  ansible.builtin.include_tasks: machines.yml
  tags:
    - libvirt
    - machines

...
