# Standards: 1.2
---
- name: Create repo file
  ansible.builtin.copy:
    src: tailscale.repo
    dest: /etc/yum.repos.d/tailscale.repo
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - tailscale

- name: Check for requirements
  register: tailscale_package_check
  changed_when: False
  failed_when: False
  ansible.builtin.command: rpm -q tailscale
  tags:
    - tailscale

- name: Include layers tasks
  when: tailscale_package_check.rc > 0
  ansible.builtin.include_tasks: layers.yml
  tags:
    - tailscale

- name: Write default config
  notify:
    - Restart tailscale
  ansible.builtin.template:
    src: default.j2
    dest: /etc/default/tailscaled
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - tailscale

- name: Write connect script
  notify:
    - Restart tailscale
  when: tailscale_authkey | default(False)
  ansible.builtin.template:
    src: script.j2
    dest: /var/usrlocal/sbin/tailscaled-autoconnect
    owner: root
    group: root
    mode: u=rwx,g=,o=
  tags:
    - tailscale

- name: Create service dir
  notify:
    - Restart tailscale
  when: tailscale_authkey | default(False)
  ansible.builtin.file:
    path: /etc/systemd/system/tailscaled.service.d
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
    state: directory
  tags:
    - tailscale

- name: Write service override
  notify:
    - Restart tailscale
  when: tailscale_authkey | default(False)
  ansible.builtin.template:
    src: override.j2
    dest: /etc/systemd/system/tailscaled.service.d/override.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - tailscale

- name: Start tailscale service
  ansible.builtin.systemd:
    name: tailscaled
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - tailscale

...
