# Standards: 1.2
---
dconf_general_profiles:
  - name: gdm
    configs:
      - name: 00-login-screen
        config: |
          [org/gnome/login-screen]
          disable-user-list=true

          [org/gnome/desktop/background]
          picture-uri="https://dl.boerger.ws/wallpapers/tower.jpg"

          [org/gnome/desktop/screensaver]
          picture-uri="https://dl.boerger.ws/wallpapers/tower.jpg"

  - name: local
    configs:
      - name: 01-desktop-config
        config: |
          [org/gnome/desktop/calendar]
          show-weekdate=true

          [org/gnome/desktop/interface]
          clock-show-weekday=true
          show-battery-percentage=true

          [org/gnome/desktop/peripherals/touchpad]
          tap-to-click=true
          two-finger-scrolling-enabled=true

          [org/gnome/desktop/wm/preferences]
          button-layout="appmenu:minimize,maximize,close"

          [org/gnome/desktop/background]
          color-shading-type="solid"
          picture-options="zoom"
          picture-uri="https://dl.boerger.ws/wallpapers/tower.jpg"
          picture-uri-dark="https://dl.boerger.ws/wallpapers/tower.jpg"
          show-desktop-icons=true

          [org/gnome/desktop/screensaver]
          color-shading-type="solid"
          picture-options="zoom"
          picture-uri="https://dl.boerger.ws/wallpapers/tower.jpg"
          picture-uri-dark="https://dl.boerger.ws/wallpapers/tower.jpg"
          lock-delay=uint32 0

          [org/gnome/desktop/notifications]
          show-in-lock-screen=false

          [org/gnome/desktop/privacy]
          old-files-age=uint32 1
          remember-recent-files=false
          remove-old-temp-files=true
          remove-old-trash-files=true
          report-technical-problems=false

          [org/gnome/settings-daemon/peripherals/touchpad]
          natural-scroll=true
          disable-while-typing=false
          tap-to-click=true
          touchpad-enabled=true

      - name: 02-shell-config
        config: |
          [org/gnome/shell]
          favorite-apps=["org.gnome.Calendar.desktop", "org.gnome.Nautilus.desktop"]

          [org/gnome/shell/extensions/aztaskbar]
          main-panel-height=(true, 40)
          show-apps-button=(true, 0)

          [org/gnome/shell/extensions/espresso]
          has-battery=true

          [org/gnome/shell/extensions/vitals]
          show-fan=true
          show-storage=false
          show-temperature=true
          show-voltage=true

          [org/gnome/shell/weather]
          automatic-location=true

          [org/gnome/shell/extensions/custom-hot-corners-extended/misc]
          show-osd-monitor-indexes=false
          {% for monitor in [0, 1, 2, 3] %}{% for space in [0] %}

          [org/gnome/shell/extensions/custom-hot-corners-extended/monitor-{{ monitor }}-bottom-left-{{ space }}]
          action="show-desktop"

          [org/gnome/shell/extensions/custom-hot-corners-extended/monitor-{{ monitor }}-bottom-right-{{ space }}]
          action="show-desktop"

          [org/gnome/shell/extensions/custom-hot-corners-extended/monitor-{{ monitor }}-top-left-{{ space }}]
          action="toggle-overview"

          [org/gnome/shell/extensions/custom-hot-corners-extended/monitor-{{ monitor }}-top-right-{{ space }}]
          action="toggle-overview"
          {% endfor %}{% endfor %}

dconf_general_configs:
  - username: thomas
    configs:
      - name: /org/gnome/shell/enabled-extensions
        value: "{{ gnome_thomas_plugins | map(attribute='id') }}"
      - name: /org/gnome/shell/favorite-apps
        value: ["org.gnome.Calendar.desktop", "org.gnome.Nautilus.desktop"]

  - username: anna
    configs:
      - name: /org/gnome/shell/enabled-extensions
        value: "{{ gnome_other_plugins | map(attribute='id') }}"

  - username: adrian
    configs:
      - name: /org/gnome/shell/enabled-extensions
        value: "{{ gnome_other_plugins | map(attribute='id') }}"

  - username: tabea
    configs:
      - name: /org/gnome/shell/enabled-extensions
        value: "{{ gnome_other_plugins | map(attribute='id') }}"

...
