# Standards: 1.2
---
flatpak_installs_general:
  - chat.revolt.RevoltDesktop
  - chat.rocket.RocketChat
  - com.authy.Authy
  - com.discordapp.Discord
  - com.getmailspring.Mailspring
  - com.github.IsmaelMartinez.teams_for_linux
  - com.google.Chrome
  - com.ktechpit.whatsie
  - com.mattermost.Desktop
  - com.mattjakeman.ExtensionManager
  - com.nextcloud.desktopclient.nextcloud
  - com.raggesilver.BlackBox
  - com.skype.Client
  - com.slack.Slack
  - com.valvesoftware.Steam
  - de.haeckerfelix.Shortwave
  - dev.k8slens.OpenLens
  - fr.free.Homebank
  - im.riot.Riot
  - io.gdevs.GDLauncher
  - io.podman_desktop.PodmanDesktop
  - net.cozic.joplin_desktop
  - net.lutris.Lutris
  - org.gnome.Calendar
  - org.gnome.Contacts
  - org.gnome.eog
  - org.gnome.Evince
  - org.gnome.Lollypop
  - org.gnome.TextEditor
  - org.gnome.Totem
  - org.onlyoffice.desktopeditors
  - org.signal.Signal
  - org.telegram.desktop
  - org.wezfurlong.wezterm

flatpak_byrefs_general:
  - name: com.onepassword.OnePassword
    url: https://downloads.1password.com/linux/flatpak/1Password.flatpakref

flatpak_filesystem_overrides:
  - /nix:ro

...
