# Standards: 1.2
---
layers_packages_general:
  - cloud-utils
  - genisoimage
  - guestfs-tools
  - libvirt
  - python3-libvirt
  - python3-lxml
  - python3-psutil
  - qemu-kvm
  - tailscale
  - zsh

...
