# Standards: 1.2
---
locales_available:
  - en_US.UTF-8
  - de_DE.UTF-8

locales_extra:
  LC_NUMERIC: de_DE.UTF-8
  LC_TIME: de_DE.UTF-8
  LC_MONETARY: de_DE.UTF-8
  LC_PAPER: de_DE.UTF-8
  LC_NAME: de_DE.UTF-8
  LC_ADDRESS: de_DE.UTF-8
  LC_TELEPHONE: de_DE.UTF-8
  LC_MEASUREMENT: de_DE.UTF-8
  LC_IDENTIFICATION: de_DE.UTF-8

locales_packs:
  - language-pack-en
  - language-pack-en-base
  - language-pack-de
  - language-pack-de-base

...
