# Standards: 1.2
---
sanoid_datasets:
  - name: rpool/USERDATA
    use_template: general
    recursive: True
    process_children_only: True

sanoid_templates:
  - name: general
    frequently: 0
    hourly: 24
    daily: 7
    monthly: 12
    yearly: 0
    autosnap: True
    autoprune: True

...
