# Standards: 1.2
---
- hosts: general
  pre_tasks:
    - name: Check ansible version
      assert:
        that: ansible_version.full is version_compare('2.10', '>=')
        msg: You must update Ansible to at least 2.10 to use this playbook

- hosts: general
  roles: []

- hosts: anubis
  roles: []

- hosts: chnum
  roles: []

- hosts: horus
  roles: []

- hosts: imhotep
  roles: []

- hosts: osiris
  roles: []

...
