# Standards: 1.2
---
- hosts: desktop
  pre_tasks:
    - name: Check ansible version
      assert:
        that: ansible_version.full is version_compare('2.10', '>=')
        msg: You must update Ansible to at least 2.10 to use this playbook

- hosts: desktop
  roles:
    - role: hosts
    - role: sudo
    - role: groups
    - role: users
    - role: root
    - role: openssh
    - role: layers
    - role: flatpak
    - role: tailscale
    - role: libvirt
    - role: gnome
    - role: dconf
    - role: distrobox
    - role: nixpkgs
    - role: dotfiles

...
