# Standards: 1.2
---
- hosts: localhost
  vars:
    ansible_connection: local
  pre_tasks:
    - name: Check ansible version
      assert:
        that: ansible_version.full is version_compare('2.10', '>=')
        msg: You must update Ansible to at least 2.10 to use this playbook

- hosts: general
  roles: []

...
