# Standards: 1.2
---
- hosts: desktop
  pre_tasks:
    - name: Check ansible version
      assert:
        that: ansible_version.full is version_compare('2.10', '>=')
        msg: You must update Ansible to at least 2.10 to use this playbook

- hosts: desktop
  roles:
    - role: hosts
    - role: sudo
    - role: groups
    - role: users
    - role: root
    - role: openssh
    - role: layers
    - role: flatpak
    - role: tailscale
    - role: libvirt
    - role: gnome
    - role: dconf
    - role: distrobox
    - role: nixpkgs

    # - role: rolehippie.gomplate
    # - role: rolehippie.helm
    # - role: rolehippie.jsonnet
    # - role: rolehippie.krew
    # - role: rolehippie.kubectl
    # - role: rolehippie.kubetools
    # - role: rolehippie.kustomize
    # - role: rolehippie.lsd
    # - role: rolehippie.mc
    # - role: rolehippie.ngrok
    # - role: rolehippie.packwiz
    # - role: rolehippie.sops
    # - role: rolehippie.starship
    # - role: rolehippie.syncthing
    # - role: rolehippie.terraform
    # - role: rolehippie.yq

    # - role: rolehippie.citrix
    # - role: rolehippie.clickup
    # - role: rolehippie.clockify
    # - role: rolehippie.vscode

- hosts: desktop
  pre_tasks:
    - name: Write profile pics
      loop:
        - thomas
        - anna
        - adrian
        - tabea
      diff: False
      copy:
        src: "profiles/{{ item }}.jpg"
        dest: "/home/{{ item }}/.face"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: u=rw,g=r,o=r
      tags:
        - profiles

...
