# Standards: 1.2
---
- hosts: general
  pre_tasks:
    - name: Check ansible version
      assert:
        that: ansible_version.full is version_compare('2.10', '>=')
        msg: You must update Ansible to at least 2.10 to use this playbook

- hosts: general
  roles:
    - role: apt
    - role: hosts
    - role: sudo
    - role: groups
    - role: users
    - role: root
    - role: openssh
    - role: base
    - role: locales
    - role: fzf
    - role: gai
    - role: modprobe
    - role: sysctl
    - role: tailscale
    - role: docker
    - role: libvirt
    - role: kubectl
    - role: cfssl

- hosts: anubis
  roles: []

- hosts: chnum
  roles: []

- hosts: horus
  roles: []

- hosts: imhotep
  roles: []

- hosts: osiris
  roles: []

...
