# Standards: 1.2
---
- src: https://github.com/rolehippie/apt
  scm: git
  version: master
- src: https://github.com/rolehippie/base
  scm: git
  version: master
- src: https://github.com/rolehippie/docker
  scm: git
  version: master
- src: https://github.com/rolehippie/fzf
  scm: git
  version: master
- src: https://github.com/rolehippie/gai
  scm: git
  version: master
- src: https://github.com/rolehippie/groups
  scm: git
  version: master
- src: https://github.com/rolehippie/hosts
  scm: git
  version: master
- src: https://github.com/rolehippie/locales
  scm: git
  version: master
- src: https://github.com/rolehippie/modprobe
  scm: git
  version: master
- src: https://github.com/rolehippie/nullmailer
  scm: git
  version: master
- src: https://github.com/rolehippie/openssh
  scm: git
  version: master
- src: https://github.com/rolehippie/root
  scm: git
  version: master
- src: https://github.com/rolehippie/sudo
  scm: git
  version: master
- src: https://github.com/rolehippie/sysctl
  scm: git
  version: master
- src: https://github.com/rolehippie/tailscale
  scm: git
  version: master
- src: https://github.com/rolehippie/users
  scm: git
  version: master

...
