# Standards: 1.2
---
- name: Include instances tasks
  loop: "{{ distrobox_general_instances + distrobox_extra_instances }}"
  loop_control:
    loop_var: user
    label: "{{ user.username }}"
  ansible.builtin.include_tasks: instances.yml
  tags:
    - distrobox

...
